# Generated by Django 4.1.1 on 2022-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default="slug",
                max_length=255,
                unique=True,
                verbose_name="Category safe URL",
            ),
            preserve_default=False,
        ),
    ]
