# Generated by Django 4.1.1 on 2023-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="min_quantity",
            field=models.FloatField(default=0.3, verbose_name="Min quantity"),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("KG", "кг"), ("PC", "шт")], default="KG", max_length=50
            ),
        ),
    ]
