# Generated by Django 4.1.1 on 2023-09-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_options_product_min_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductExternalId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source", models.CharField(max_length=128)),
                ("external_id", models.CharField(max_length=128)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ids",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("data_source", "external_id")},
            },
        ),
    ]
