# Generated by Django 4.1.1 on 2022-11-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="display_on_home_page",
            field=models.BooleanField(
                default=False, verbose_name="Display on home page"
            ),
        ),
    ]
