# Generated by Django 4.1.1 on 2022-11-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("store", "0004_remove_product_display_on_home_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="categories.category"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
