version: "3.9"

services:
  backend:
    restart: always
    build: .
    command: gunicorn core.wsgi:application -w 2 -b :8080 -t 120
    ports:
      - "8080:8080"
    volumes:
      - /var/www/persistentdata/static:/var/www/static
      - /var/www/persistentdata/media:/var/www/media  
    env_file:
      - .env   
