version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media

  db:
    restart: always
    image: postgres
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mixaluch-shop-admin
      - POSTGRES_PASSWORD=MBppwV5&_Ny9
      - POSTGRES_DB=mixaluch-db
