version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "92.51.39.66:8080:8080"
    volumes:
      - .:/app
      - /var/www/persistentdata/static:/var/www/static
      - /var/www/persistentdata/media:/var/www/media     
