version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
    command: gunicorn core.wsgi:application -b :8080
    ports:
      - "8080:8080"
    volumes:
      - /var/www/persistentdata/static:/var/www/static
      - /var/www/persistentdata/media:/var/www/media   
    network_mode: "host"
