# Generated by Django 4.1.1 on 2023-09-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="markdown_text",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
