# Generated by Django 4.1.1 on 2022-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="second_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
