# Generated by Django 4.1.1 on 2022-09-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
