# Generated by Django 4.1.1 on 2022-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_slug"),
        ("cart", "0003_rename_price_cartitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(to="store.product"),
        ),
    ]
