# Generated by Django 4.1.1 on 2022-10-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
