# Generated by Django 4.1.1 on 2023-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_data",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROCESS", "В обработке"),
                    ("ACCEPTED", "Принят"),
                    ("COLLECTED", "Собран"),
                    ("IN_DELIVERY", "В доставке"),
                    ("COMPLETED", "Выполнен"),
                ],
                default="IN_PROCESS",
                max_length=30,
            ),
        ),
    ]
