# Generated by Django 4.1.1 on 2023-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_data",
            field=models.JSONField(default=dict),
        ),
    ]
