# Generated by Django 4.1.1 on 2023-01-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_email_remove_order_second_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products_total",
            new_name="total_sum",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total",
            new_name="total_sum_with_delivery",
        ),
    ]
