# Generated by Django 4.1.1 on 2024-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.CharField(default="AS_SOON_AS_POSSIBLE", max_length=64),
        ),
    ]
